version: '2'
services:
  jenkins-master:
    build: .
    image: mknapik/jenkins:2.19.1
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins_home:/var/jenkins_home
